<script>
	import { CldImage } from 'svelte-cloudinary';
	import Support from '$components/Support.svelte';
	import { MetaTags, JsonLd } from 'svelte-meta-tags';
</script>

<svelte:head>
	<title>About</title>
	<meta name="description" content="About CCCD Jamaica - Our Mission, Vision, and Beliefs" />
</svelte:head>

<MetaTags
    title="About Us - Caribbean Christian Centre for the Deaf"
    description="Learn about the mission, vision, and history of Caribbean Christian Centre for the Deaf (CCCD) Jamaica. Discover how we're empowering the Deaf community through education and support."
    canonical="https://cccd.org.jm/about"
    openGraph={{
        url: 'https://cccd.org.jm/about',
        title: 'About CCCD Jamaica - Empowering the Deaf Community',
        description: 'Discover the mission and impact of Caribbean Christian Centre for the Deaf. Learn how we\'re transforming lives through education and support for the Deaf in Jamaica.',
        images: [
            {
                url: 'https://res.cloudinary.com/shinkirin/image/upload/v1726612157/cccd/graduatesfromcccd.webp',
                width: 800,
                height: 600,
                alt: 'CCCD Jamaica Deaf Students'
            }
        ],
    }}
    twitter={{
        handle: '@CCCDJamaica',
        site: '@CCCDJamaica',
        cardType: 'summary_large_image',
    }}
/>

<JsonLd
    schema={{
        "@context": "https://schema.org",
        "@type": "NGO",
        name: "Caribbean Christian Centre for the Deaf",
        alternateName: "CCCD Jamaica",
        url: "https://cccd.org.jm",
        logo: "https://res.cloudinary.com/shinkirin/image/upload/v1722901294/cccd_wordpress/cropped-cccdLogo-drupal.webp",
        sameAs: [
            "https://www.facebook.com/cccdjamaica",
            "https://www.instagram.com/cccdjamaica/",
            "https://www.youtube.com/@caribbeanchristiancentre"
        ],
        description: "Caribbean Christian Centre for the Deaf (CCCD) is dedicated to empowering the Deaf community in Jamaica through education, vocational training, and spiritual nurturing.",
    }}
/>

<!-- Accessibility Checks
	1. silktide: WCAG 2.2 AA Compliance on 2024-09-22.
-->

<section class="bg-white py-12">
	<div class="container mx-auto px-4">
		<h2 class="text-3xl font-bold text-center mb-8 text-red-900">Our Mission and Vision</h2>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-8">
			<div>
				<h3 class="text-2xl font-semibold mb-4">Our Mission</h3>
				<p class="text-black text-md font-semibold">
					At CCCD Jamaica, our mission is to Reach, Teach, and Nurture the Deaf community across the island. We strive to provide comprehensive education, vocational training, and spiritual guidance to ensure that every Deaf individual can lead a fulfilling and independent life.
				</p>
				<div class="mt-4 flex flex-col items-center">
					<CldImage
						src="https://res.cloudinary.com/shinkirin/image/upload/v1726533553/cccd_wordpress/cccdstudent1.webp"
						alt="Our students achieving their goals through education"
						width="400"
						height="400"
						class="w-full h-auto rounded-lg border-2 border-blue-800"
					/>
					<p class="text-md text-gray-900 mt-2">Our students achieving their goals through education</p>
				</div>
			</div>
			<div>
				<h3 class="text-2xl font-semibold mb-4">Our Vision</h3>
				<p class="text-black text-md font-semibold">
					Our vision is a Jamaica where the Deaf community is fully integrated, empowered, and able to contribute meaningfully to society. We believe in the potential of every Deaf person and are committed to creating opportunities for growth and development.
				</p>
				<div class="mt-4 flex flex-col items-center">
					<CldImage
						src="https://res.cloudinary.com/shinkirin/image/upload/v1726533554/cccd_wordpress/cccdstudent2.webp"
						alt="Empowering the Deaf community for a brighter future"
						width="400"
						height="400"
						class="w-full h-auto rounded-lg border-2 border-blue-800"
					/>
					<p class="text-md text-gray-900 mt-2">Empowering the Deaf community for a brighter future</p>
				</div>
			</div>
		</div>
		<div class="mt-8">
			<blockquote class="text-red-800  text-lg font-semibold text-center italic pl-4 py-2">
				&quot;Through our dedicated programs and initiatives, we aim to break down barriers and build a more inclusive and supportive environment for the Deaf in Jamaica.&quot;
			</blockquote>
		</div>
	</div>
</section>
<section id="statement-of-faith" class="bg-blue-50 py-12 border-t-2 border-blue-800">
	<div class="container mx-auto px-4">
		<h2 class="text-3xl font-bold text-center mb-8 text-red-900">Our Beliefs</h2>
		<div class="flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/3">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726422136/cccd/christ-dall-e-jamaica.webp"
					alt="Image of Christ generated by Dall-E with Jamaican students in the background"
					width="400"
					height="600"
					class="w-full h-auto rounded-lg shadow-md border-2 border-blue-800"
				/>
			</div>
			<div class="w-full md:w-2/3 prose max-w-none">
				<p class="mb-4 text-black text-md font-semibold">We believe:</p>
				<ul class="list-disc list-inside text-black text-md font-semibold pl-4 space-y-4 marker:text-red-800">
					<li>In One God, who has revealed Himself in Scripture through the Old and New Testaments as three Persons; Father, Son and Holy Spirit</li>
					<li>God is Creator and Sustainer of all seen and unseen. God is eternal, unchanging, all-knowing, and good. God is continually at work guiding His creation.</li>
					<li>In God the Father - who loves each of us with unconditional and eternal love.</li>
					<li>In Jesus - the Son of God, Word became flesh. Jesus is our Savior - He came to earth fully God and fully man - He suffered, died, was buried, and rose victorious over sin and death. Through Jesus and His perfect obedience to God, we are offered forgiveness and redemption.</li>
					<li>In the Holy Spirit - sent by the Father and Son to convict and renew. Counselor, teacher, comforter, helper, advocate - uniting us for the glory of God.</li>
					<li>That following Jesus Christ brings new life and we are empowered to live as we were created to as sons and daughters of God, accomplishing all for His glory.</li>
					<li>In the promises of God giving us a hope and future, both now and life everlasting – Where someday every tribe, tongue, and nation will join together to worship God and enjoy Him forever!</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<section id="board" class="bg-gold-100 py-12 border-t-2 border-blue-800">
	<div class="container mx-auto px-4">
		<h2 class="text-3xl font-bold text-center mb-8 text-red-900">Our Board Members</h2>
		<div class="grid grid-cols-1 md:grid-cols-3 gap-8">
			<div class="bg-blue-900 p-6 rounded-lg shadow-md">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1735497715/leon-cccd_qspc07.webp"
					alt="Leon Samms - CCCD Jamaica CEO and Company Secretary"
					width="300"
					height="300"
					class="w-full h-auto rounded-full mb-4"
				/>
				<h3 class="text-xl font-semibold mb-2 text-white">Leon Samms</h3>
				<p class="text-white font-semibold italic">CEO and Company Secretary</p>
				<p class="mt-2 text-white">Leon is a trained project management and development specialist with over 7 years of experience,  and with over 15 years of Christian Ministry experience. His heart for Ministry has led him to join the CCCD Family in 2021 as its CEO. He hold a Bachelor of Business Administration from the University of Technology, Jamaica and a Master's Degree in Public Administration (community and rural development), form the Yeungnam University, South Korea.</p>
		</div>
			<div class="bg-blue-900 p-6 rounded-lg shadow-md">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726535311/cccd/ben-beukema.webp"
					alt="Ben Beukema - CCCD Jamaica Director"
					width="300"
					height="300"
					class="w-full h-auto rounded-full mb-4"
				/>
				<h3 class="text-xl font-semibold mb-2 text-white">Ben Beukema</h3>
				<p class="text-white font-semibold italic">Director</p>
				<p class="mt-2 text-md text-white">Ben&apos;s first trip to Jamaica to serve with the ministry was in 2003 when he was still in high school. He began serving full-time with the ministry in January of 2012 as a missionary at the Jamaica Deaf Village. In 2018 he changed roles and began leading the CCCD US Office. He has served on the board of directors since December 2019.</p>
			</div>
			<div class="bg-blue-900 p-6 rounded-lg shadow-md">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726534357/cccd/Kent_Mogler_Headshot.webp"
					alt="Kent Mogler - CCCD Jamaica Treasurer"
					width="300"
					height="300"
					class="w-full h-auto rounded-full mb-4"
				/>
				<h3 class="text-xl font-semibold mb-2 text-white">Kent Mogler</h3>
				<p class="font-semibold mb-2 text-white italic">Treasurer, Finance Committee chairperson.</p>
				<p class="mt-2 text-md text-white">Kent&apos;s engagement with CCCD cam about through his missionary engagement with Harvest Call Jamaica.  He and his wife Mary reside in St. Paul, Minnesota.   He has 42 years of professional finance and operations positions, all within the food production industry.  Kent enjoys mentoring and supporting the CCCD finance team members at each campus.</p>
			</div>
		</div>
	</div>
</section>
<section class="bg-white py-12 border-t-2 border-blue-800">
	<div class="container mx-auto px-4">
		<h2 class="text-3xl font-bold text-center mb-8 text-red-900">History of CCCD</h2>
		
		<div class="mb-8 flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/2">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1720369817/cccd/cccdhistory.webp"
					alt="Early photos of CCCD in Jamaica"
					width="600"
					height="450"
					class="w-full h-auto rounded-lg shadow-md"
				/>
			</div>
			<div class="w-full md:w-1/2">
				<h3 class="text-2xl font-semibold mb-4 text-red-700">Founded in 1958</h3>
				<p class="mb-4 text-md font-semibold">In February of 1957, Reverend Willis Ethridge and his wife, Mildred, left their home in Ontario, Canada. Their mission was to start the Christian Deaf Fellowship Center in Kingston, Jamaica. Upon arrival in Jamaica, they found a greater need than they had imagined, and felt the Lord calling them to open a school. They were soon joined by Paula Montgomery, the first Deaf American missionary.</p>
				<p class="mb-4 text-md font-semibold">Together, the three missionaries were offered a one-year lease of a property in Manchester Parish, Jamaica, where they opened a school with eight students and a staff of three.</p>
			</div>
		</div>

		<div class="mb-8 flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/2">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726611569/cccd/knockpatrickcampus.jpg"
					alt="Deaf student and her mother at the Knockpatrick Campus"
					width="600"
					height="450"
					class="w-full h-auto rounded-lg shadow-md"
				/>
			</div>
			<div class="w-full md:w-1/2">
				<h3 class="text-2xl font-semibold mb-4">The Knockpatrick Campus</h3>
				<p class="mb-4 text-md font-semibold">The school continued to gain momentum, and in September 1962 moved to its present location in Knockpatrick. By 1967 there were 40 students, and today this beautiful campus serves around 70 students.</p>
			</div>
		</div>

		<div class="mb-8 flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/2">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726611096/cccd/montegobaycccd.webp"
					alt="Active Deaf students at CCCD in Montego Bay Campus, Montego Bay, Jamaica"
					width="600"
					height="450"
					class="w-full h-auto rounded-lg shadow-md"
				/>
			</div>
			<div class="w-full md:w-1/2">
				<h3 class="text-2xl font-semibold mb-4">The Montego Bay Campus</h3>
				<p class="mb-4 text-md font-semibold">In 1990, a second campus was added in Montego Bay, Jamaica, built on 7.5 acres of generously donated land. This school opened in August 1994 with three children. Today it serves around 40 students in our furthering education program (CADE).</p>
			</div>
		</div>

		<div class="mb-8 flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/2">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726536326/cccd/cccdstudents4.webp"
					alt="Jamaica Deaf Students studying at CCCD"
					width="600"
					height="450"
					class="w-full h-auto rounded-lg shadow-md"
				/>
			</div>
			<div class="w-full md:w-1/2">
				<h3 class="text-2xl font-semibold mb-4">The Kingston Campus</h3>
				<p class="mb-4 text-md font-semibold">In July 1994, the CCCD reopened the old Christian Deaf Fellowship campus in the heart of Kingston as a new CCCD school. Kingston is home to half the population of Jamaica, as well as many Deaf who do not have access to the Knockpatrick and MoBay campuses. Today, the Kingston campus serves around 40 students and is home to the Deaf Can! Coffee enterprise.</p>
			</div>
		</div>

		<div class="mb-8 flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/2">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726536329/cccd/jamaicaDeafvillage.webp"
					alt="Jamaica Deaf Village"
					width="600"
					height="450"
					class="w-full h-auto rounded-lg shadow-md"
				/>
			</div>
			<div class="w-full md:w-1/2">
				<h3 class="text-2xl font-semibold mb-4">The Jamaica Deaf Village</h3>
				<p class="mb-4 text-md font-semibold">The three school campuses continued to run smoothly, and graduated class after class -- but the Deaf graduating from high school still struggled to find employment. Employers did not have the time or resources to devote to learning to communicate with the Deaf, and did not hire them.</p>
				<p class="mb-4 text-md font-semibold">No job means no money, and no money means that, despite their education and potential, the Deaf graduates were unable to provide for their own basic needs. Many turned to desperate means to obtain food, clothing, and shelter.</p>
				<p class="	mb-4 text-md font-semibold">And so in June of 1984, the CCCD ministry began development of the 100-acre Jamaica Deaf Village, which would serve as a safe place where Deaf adults and their families could live in community, attend worship, and find meaningful employment.</p>
			</div>
		</div>

		<div class="mb-8 flex flex-col md:flex-row items-start gap-8">
			<div class="w-full md:w-1/2">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/v1726611183/cccd/Deafvillagechurch.webp"
					alt="Church at the Deaf Village outside Knockpatrick, J"
					width="600"
					height="450"
					class="w-full h-auto rounded-lg shadow-md"
				/>
			</div>
			<div class="w-full md:w-1/2">
				<h3 class="text-2xl font-semibold mb-4">The Factory & Church</h3>
				<p class="mb-4 text-md font-semibold">The Jamaica Deaf Village (JDV) campus continued to grow with the addition of a church, a woodworking factory, apartment complexes for the Deaf, and more -- none of which could have been constructed without the assistance of mission teams.</p>
				<p class="mb-4 text-md font-semibold">Finally, in 2002, after many years of miracles mixed with trying circumstances, the first villagers moved onto campus, and the first steam-bent wooden rocking chair was manufactured in the factory.</p>
				<p class="mb-4 text-md font-semibold">Shortly thereafter, the first church service was held at the village, led by Rev. Gary Williams, who plants Deaf churches within the hearing churches of Kingston. There were nearly 60 Deaf present that Sunday, and ever since, the Deaf have been worshipping, fellowshipping, and growing in Christ Jesus at JDV.</p>
			</div>
		</div>

		<div>
			<h3 class="text-2xl font-semibold mb-4 text-red-900">The Future</h3>
			<p class="mb-4 text-md font-semibold">We have the privilege of knowing, serving, and trusting in a God who loves us. Help us to spread the word of Jesus Christ to the Deaf in Jamaica. You can do this in many ways:</p>
			<ul class="list-disc list-inside mb-4 pl-4 text-md font-semibold">
				<li>Keep us operating by giving to our General Fund</li>
				<li>Sponsor one of the children on our campuses</li>
				<li>Bring a team to visit and help us continue to build and grow our campuses</li>
				<li>Continue to spread the word of the work we're doing here in Jamaica</li>
			</ul>
			<p class="mb-4 text-md font-semibold">We hope that, with your help, the mission of the CCCD can continue to expand and grow.</p>
			<div class="mt-8 flex flex-col items-center">
				<CldImage
					src="https://res.cloudinary.com/shinkirin/image/upload/c_scale,w_1200/v1726536841/cccd/20240725_105724.webp"
					alt="CCCD Deaf Village"
					width="1200"
					height="400"
					class="w-full max-w-4xl h-auto rounded-lg shadow-md"
				/>
				<p class="mt-2 text-md text-gray-900 font-semibold italic">Together, we can build a brighter future for the Deaf community in Jamaica</p>
			</div>
		</div>
	</div>
</section>
<Support />
